server:
  port: 8000

dubbo:
  application:
    name: yangmao-live-api-application
    qos-enable: false
  registry:
    address: nacos://localhost:8848?namespace=d8d774d5-a63b-4a86-b4b9-e0a949e41e73
